# Generated by Django 2.2.20 on 2021-04-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=20)),
                ('items', models.CharField(max_length=20)),
                ('order_date', models.DateField()),
                ('pickup_date', models.DateField()),
                ('truck', models.CharField(choices=[('1', 'United'), ('2', 'Ashley'), ('3', 'Serta'), ('4', 'Sealy'), ('5', 'Freight')], max_length=100)),
                ('order_type', models.CharField(choices=[('1', 'PH'), ('2', 'Layaway')], max_length=100)),
                ('order_isreserved', models.BooleanField()),
            ],
        ),
    ]
