# Generated by Django 2.2.20 on 2021-04-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.CharField(max_length=100),
        ),
    ]
