# Generated by Django 2.2.20 on 2021-04-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210421_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('ph', 'PH'), ('layaway', 'Layaway')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='truck',
            field=models.CharField(choices=[('united', 'United'), ('ashley', 'Ashley'), ('serta', 'Serta'), ('sealy', 'Sealy'), ('freight', 'Freight')], max_length=100),
        ),
    ]
