# Generated by Django 2.2.20 on 2021-04-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210425_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_ismarked',
            field=models.BooleanField(default=False),
        ),
    ]
