# Generated by Django 2.2.20 on 2021-04-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_order_order_ismarked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_ismarked',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_isreserved',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('ph', 'PH'), ('layaway', 'Layaway')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='truck',
            field=models.CharField(blank=True, choices=[('united', 'United'), ('ashley', 'Ashley'), ('serta', 'Serta'), ('sealy', 'Sealy'), ('freight', 'Freight')], max_length=100),
        ),
    ]
