# Generated by Django 2.2.20 on 2021-04-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210427_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_ismarked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_isreserved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
