# Generated by Django 2.2.20 on 2021-05-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210517_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_ismarked',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_isreserved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
