# Generated by Django 2.2.20 on 2021-05-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210517_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_ismarked',
        ),
    ]
