# Generated by Django 2.2.20 on 2021-05-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_order_order_ismarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_ismarked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
