# Generated by Django 2.2.20 on 2021-05-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210520_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_isreserved',
            field=models.NullBooleanField(default=False),
        ),
    ]
