# Generated by Django 2.2.20 on 2021-05-26 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210520_1448'),
        ('home', '0011_order_order_ismarked'),
    ]

    operations = [
    ]
