# Generated by Django 2.2.20 on 2021-05-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210526_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_ismarked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
